[package]
name = "machine_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.machine]
path = ".."

[lib]
name = "machine_wasm"
crate-type = ["cdylib"]
[dependencies]
wasm-bindgen = "0.2.87"